services:
  mineru-api:
    image: mineru:latest
    container_name: mineru_factory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '32gb'
    ipc: host
    ports:
      - "8000:8000"
    volumes:
      # 这里的变量会自动读取同目录下的 .env 文件
      - ${DATA_DIR}:/app/data
    stdin_open: true
    tty: true
    # command: ["python3", "-m", "mineru.cli.fast_api", "--host", "0.0.0.0", "--port", "8000"]
    command: /bin/bash